### ISSUE TITLE
No DB found!

### ISSUE THREAD

**Issue by netcriptus** [rudolfce/scrapper#7]
Good to see the project has a DB now, except that I cannot use it. Now I run the project and get a internal server error, because it tries to connect to an DB that does not exist!

The `README` has no instructions on how to initialize the DB. Spoiler alert: there's a catch here :wink: 

Discuss your solution before implementing it this time.

**Comment by rudolfce** [comment]
I've been studying this topic and found a few viable solutions. To skip using SQL Queries directly, I found that SQLAlchemy-Utils provides a useful function create_database, as well as a database_exists to check for existence.

The solution I believe would be the nicest would be to add SQLAlchemy-Utils to the requirements list and proceed adding a verification when runserver is called. If database exists as described in db_data.json, it then tries the connection to it. Otherwise, it exits gracefully hinting the new manager command create_db that I'm about to write, which creates it and generates the "users" table inside from the Base.metadata.create_all() method (from db_stuff/__init__.py - all praise ORM).

**Comment by netcriptus** [comment]
Great!

Only that the `create_db` command is usually called `init_db`. It's not mandatory, but a good idea to keep this way.

Check [this](https://github.com/netcriptus/EF_scraper/blob/master/manage.py#L17) `manage.py`. There are more db related commands, you should implement the ones you can understand.
